// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            Category = "Appetizer",
                            Description = "Punjabi Samosa",
                            ImageURL = "",
                            Name = "Samosa",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 2L,
                            Category = "Appetizer",
                            Description = "Paneer Tikka with Marination",
                            ImageURL = "",
                            Name = "Paneer Tikka",
                            Price = 20m
                        },
                        new
                        {
                            ProductId = 3L,
                            Category = "Appetizer",
                            Description = "Mumbai Pav Bhaji",
                            ImageURL = "",
                            Name = "Pav Bhaji",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = 4L,
                            Category = "Appetizer",
                            Description = "Mumbai Pani Puri",
                            ImageURL = "",
                            Name = "Pani Puri",
                            Price = 5m
                        },
                        new
                        {
                            ProductId = 5L,
                            Category = "Main Course",
                            Description = "South Indian Masala Dosa",
                            ImageURL = "",
                            Name = "Masala Dosa",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = 6L,
                            Category = "Main Course",
                            Description = "Hyderabadi Chicken Biryani",
                            ImageURL = "",
                            Name = "Chicken Biryani",
                            Price = 30m
                        },
                        new
                        {
                            ProductId = 7L,
                            Category = "Main Course",
                            Description = "Bombay Veg Biryani",
                            ImageURL = "",
                            Name = "Veg Biryani",
                            Price = 15m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
